/**
 * Round-trip preservation tests.
 *
 * Each test verifies that a specific markdown construct passes through the
 * parse → stringify pipeline without any transformation.  This file acts as a
 * living specification of what the pipeline MUST NOT corrupt.
 *
 * Covered constructs:
 *  - Obsidian wikilinks  [[Page]] / ![[image.png]]
 *  - Angle-bracket expressions containing asterisks  <* … *>
 *  - Templater JS blocks  <%* … %>
 *  - Nested unordered lists (all levels use the canonical `*` bullet)
 *  - YAML front-matter
 *  - Emphasis that uses `*` as a delimiter (*italic*)
 *  - Escaped asterisks that must remain escaped  \*literal\*
 */
import { describe, it, expect } from 'vitest';
import { parseMarkdown, stringifyMarkdown } from '../src/markdown/parse.js';

function roundTrip(content: string): string {
  return stringifyMarkdown(parseMarkdown(content));
}

// ---------------------------------------------------------------------------
// Wikilinks
// ---------------------------------------------------------------------------

describe('round-trip: wikilinks', () => {
  it('preserves page wikilink [[Page Name]]', () => {
    const src = '[[Some Link]]\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves inline image wikilink ![[file.png]]', () => {
    const src = '![[Projects/2022-05-07_09.18.50.png]]\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves wikilink with underscores in filename', () => {
    const src = '![[archive/meeting_notes_2024.png]]\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves wikilink inside a task list item', () => {
    const src = '* [ ] Review ![[diagram_v2.png]]\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves multiple wikilinks on the same line', () => {
    const src = 'See [[Note 1]] and also [[Note 2]] for details.\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves nested list with wikilinks at each level', () => {
    const src = '* Top level [[link]]\n  * Nested [[link2]]\n    * Deep [[link3]]\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves wikilink with path separator', () => {
    const src = 'See [[Archive/Old Project]] for history.\n';
    expect(roundTrip(src)).toBe(src);
  });
});

// ---------------------------------------------------------------------------
// Asterisks in non-emphasis contexts
// ---------------------------------------------------------------------------

describe('round-trip: asterisks in non-emphasis contexts', () => {
  it('preserves <* … *> angle-bracket tag syntax', () => {
    // Both * are inert: the first is not left-flanking (followed by space),
    // the second is not right-flanking (preceded by space).
    const src = '<* something *>\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves Templater <%* … %> block syntax', () => {
    // The * in <%* is not left-flanking (followed by space).
    const src = '<%* const title = tp.file.title; %>\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves Templater <%* in a task', () => {
    const src = '* [ ] Generated by <%* tR += tp.file.title %>\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('does NOT strip escaping from * that would form emphasis', () => {
    // \*foo\* in the source is literal text: the pipeline must keep it escaped
    // so that re-parsing still produces a text node, not <em>foo</em>.
    const src = '\\*foo\\* bar\n';
    const out = roundTrip(src);
    // The output representation may differ slightly but the rendered semantics
    // must be identical: the * characters must not form an emphasis node.
    const tree = parseMarkdown(out);
    const para = tree.children[0] as import('mdast').Paragraph;
    // All children must be text — no emphasis node.
    for (const child of para.children) {
      expect(child.type).toBe('text');
    }
  });

  it('preserves actual *emphasis* unchanged', () => {
    // *foo* should remain as *foo* (emphasis node round-trips cleanly).
    const src = '*foo* bar\n';
    expect(roundTrip(src)).toBe(src);
  });
});

// ---------------------------------------------------------------------------
// Nested lists
// ---------------------------------------------------------------------------

describe('round-trip: nested lists', () => {
  it('preserves 2-space nested unordered list', () => {
    const src = '* Item 1\n  * Nested 1\n  * Nested 2\n* Item 2\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves three-level nesting', () => {
    const src = '* Level 1\n  * Level 2\n    * Level 3\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves nested task lists', () => {
    const src =
      '* [ ] Parent task\n' +
      '  * [ ] Child task\n' +
      '    * [ ] Grandchild\n' +
      '  * [ ] Another child\n' +
      '* [ ] Second parent\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves ordered list nested inside unordered', () => {
    const src = '* Item\n  1. First\n  2. Second\n* Another item\n';
    expect(roundTrip(src)).toBe(src);
  });

  it('preserves loose nested list (blank lines between items)', () => {
    const src = '* Item 1\n\n  * Nested 1\n\n  * Nested 2\n\n* Item 2\n';
    expect(roundTrip(src)).toBe(src);
  });
});

// ---------------------------------------------------------------------------
// YAML front-matter
// ---------------------------------------------------------------------------

describe('round-trip: YAML front-matter', () => {
  it('preserves front-matter block via normalizeFileContent', async () => {
    // normalizeFileContent splits frontmatter from body before parse/stringify,
    // so the YAML block is never fed to remark and cannot be corrupted.
    const { normalizeFileContent } = await import('../src/engine/runner.js');
    const src = '---\ntitle: My Note\ntags:\n  - project\n---\n\n# Heading\n\nBody text.\n';
    expect(normalizeFileContent(src)).toBe(src);
  });
});
